
ROTATE_DEFAULT = 0
ZOOM_DEFAULT = 0

# LAANEEVNE default values 
HOUSE_PRICE         = 4500000

PERSON1_PENSION     = 10
PERSON1_LOEN        = 53000
PERSON1_GAELD       = 0
PERSON1_SAVINGS     = 1350000

PERSON2_PENSION     = 10
PERSON2_LOEN        = 50000
PERSON2_GAELD       = 0
PERSON2_SAVINGS     = 150000

SAMLET_INDTAEGT     = 0
MAX_LAAN            = 0 
LOEN_EFTER_SKAT1    = 0 
LOEN_EFTER_SKAT2    = 0 
SKATTEPROCENT1      = 0
SKATTEPROCENT2      = 0 
SAMLET_INDTAEGT     = 0 

# FREMTIDIG 
REAL_LÅNPERIODE    = 30 
REAL_NOMINEL       = 2.25
REAL_BIDRAGSSATS   = 0.85
REAL_TERMINER      = 4
AFDRAGSFRI         = False
REAL_LAANEBEREGNING = {}

REAL_LÅNPERIODE    = 30 
BANK_NOMINEL       = 4.25
BANK_TERMINER      = 4
BANK_LAANEBEREGNING = {}

RENTE_BETALING              = 0 
RENTE_AFDRAG                = 0
RENTEFRADRAGPROCENT         = 0 
RENTEFRADRAG                = 0 
SAMLET_YDELSE               = 0 
FASTE_UDGIFTER              = 0 
FASTE_UDGIFTER_INKL_YDELSER = 0 
RÅDIGHEDSBELØB              = 0 


# UDGIFTER
EJER_UDGIFT                 = 6500
FORBRUG                     = 1500
MAD_DAGLIGVARE              = 2500
TRANSPORT                   = 3500
FORSIKRINGER                = 700
TELEFON_INT_MEDIE           = 1000
PERSONLIG_PLEJE_TOEJ        = 500
FRITID_FORNOEJELSER         = 1500
PASNING_FRITIDSAKTIVITETER  = 0 
FLEXUDGVAR1                 = 0
FLEXUDGSTRING1              = "Indsæt Beskrivelse"
FLEXUDGVAR2                 = 0
FLEXUDGSTRING2              = "Indsæt Beskrivelse"
FLEXUDGVAR3                 = 0
FLEXUDGSTRING3              = "Indsæt Beskrivelse"
    
GÆLDSFAKTOR                 = 0
BANKLÅN                     = 0
REALKREDITLÅN               = 0
SAMLETLÅN                   = 0
ALLEFASTEUDGIFTER           = 0
FORVENTETPRIS               = 0


# PERSONLIGE OPLYSNINGER
FORNAVN1 = "Fornavn" 
EFTERNAVN1 = "Efternavn"      
TELEFON1 = 10203040
MAIL1 = 'mail@mail.dk'
ADRESSES_VEJ1 = "Vej"
ADRESSE_POSTNR1 = "Postnummer"
ADRESSE_BY1 = "By"
ADRESSE_SAMLET1 = "vej_by_postnummer"
FØDSELSDAG_DAG1 = 1 
FØDSELSDAG_MÅNED1 = 1 
FØDSELSDAG_ÅR1 = 1990
DATO_DMO1 = "DD/MM/YYYY"

FORNAVN2 = "Fornavn" 
EFTERNAVN2 = "Efternavn"
TELEFON2 = 10203040
MAIL2 = 'mail@mail.dk'             
ADRESSES_VEJ2 = "Vej"
ADRESSE_POSTNR2 = "Postnummer"
ADRESSE_BY2 = "By"
ADRESSE_SAMLET2 = "vej_by_postnummer"
FØDSELSDAG_DAG2 = 1 
FØDSELSDAG_MÅNED2 = 1 
FØDSELSDAG_ÅR2 = 1990
DATO_DMO2 = "DD/MM/YYYY"

NY_ADDR = "Vejnavn på ny adresse"
LINK_ADDR = "http://"
RAPPORTNAVN = "Låne_Rapport.pdf"


# LAANEEVNE default values 
BLUR_DEFAULT = 0
CONTRAST_DEFAULT = 0
EFFECT_OPTIONS = ['None', 'Emboss', 'Find edges', 'Contour', 'Edge enhance']
FLIP_OPTIONS = ['None', 'X', 'Y', 'Both']

# COLORS
BLUE_COLOR='#1f6aa5'
FG_COLOR ='#64686b'
DARK_GREY = '#4a4e51'
BRIGHTNESS_DEFAULT = 1
INVERT_DEFAULT = False
VIBRANCE_DEFAULT = 1
GRAYSCALE_DEFAULT = False 
BACKGROUND_COLOR = "#242424"
WHITE = "#FFF"
CLOSE_RED = "#8a0606"

TIME_OPTIONS = ['Max', '1 Year', '6 Months', 'Month', 'Week']
INPUT_BG_COLOR = "#121a2c"
BG_COLOR = "#19233c"
TICK_COLOR = "#EEEEEE"
HIGHLIGHT_COLOR = "#21eaad" 
TEXT_COLOR = "#FFFFFF"
TITLE_HEX_COLOR = 0x003c2319

DROPDOWN_MAIN_COLOR = '#444'
DROPDOWN_HOVER_COLOR = '#333'
DROPDOWN_MENU_COLOR = '#666'

# PFD Export tab 
TEXTFORMAT = "Helvetica"
 
# Forhandling variables
UDBUDSPRIS          = 5900000
FORVENTET_PROCENT   = 8    
FORVENTET_PRIS      = 5000000    
RUNDE1_PROCENT      = 65
RUNDE1_PRIS         = 3260000
RUNDE2_PROCENT      = 85
RUNDE2_PRIS         = 4260000
RUNDE3_PROCENT      = 95
RUNDE3_PRIS         = 4760000
RUNDE4_PROCENT      = 100
RUNDE4_PRIS         = 5000000
AGGRESSIVITET       = 1
FORHANDLING_TITEL   = "FORHANDLING"
FORHANDLING_STRATEGI= "STRATEGI"
FORHANDLING_LØSØRE  = "LØSØRE"
FORHANDLING_ARGUMENT= "ARGUMENTATION"


# RENOVERING    
BUDGETNAVN      = "BUDGET NAVN"
KONTAKT_NAVN    = 'Kontaktperson'
KONTAKT_TELEFON = 'Telefon'
KONTAKT_MAIL    = 'E-mail'