USE fundora;

CREATE TABLE finansiering (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bruger_id INT NOT NULL,
    huspris DECIMAL(12,2),
    forventet_pris DECIMAL(12,2),
    p1_loen DECIMAL(10,2),
    p1_gaeld DECIMAL(10,2),
    p1_savings DECIMAL(10,2),
    p1_pension_proc DECIMAL(5,2),
    skat1_proc DECIMAL(5,2),
    loen_efter_skat1 DECIMAL(10,2),
    p2_loen DECIMAL(10,2),
    p2_gaeld DECIMAL(10,2),
    p2_savings DECIMAL(10,2),
    p2_pension_proc DECIMAL(5,2),
    skat2_proc DECIMAL(5,2),
    loen_efter_skat2 DECIMAL(10,2),
    samlet_indtaegt DECIMAL(10,2),
    real_laan_periode INT,
    real_nominel_rente DECIMAL(5,2),
    real_bidragssats DECIMAL(5,2),
    real_terminer INT,
    afdragsfri BOOLEAN,
    bank_nominel_rente DECIMAL(5,2),
    bank_terminer INT,
    rente_betaling DECIMAL(10,2),
    rente_afdrag DECIMAL(10,2),
    rentefradrag_proc DECIMAL(5,2),
    rentefradrag DECIMAL(10,2),
    samlet_ydelse DECIMAL(10,2),
    ejer_udgift DECIMAL(10,2),
    forbrug DECIMAL(10,2),
    mad_dagligvare DECIMAL(10,2),
    transport DECIMAL(10,2),
    forsikringer DECIMAL(10,2),
    telefon_internet_medie DECIMAL(10,2),
    personlig_pleje_toej DECIMAL(10,2),
    fritid_fornoejelser DECIMAL(10,2),
    pasning_fritid DECIMAL(10,2),
    flex1_beskrivelse VARCHAR(255),
    flex1_beloeb DECIMAL(10,2),
    flex2_beskrivelse VARCHAR(255),
    flex2_beloeb DECIMAL(10,2),
    flex3_beskrivelse VARCHAR(255),
    flex3_beloeb DECIMAL(10,2),
    gaeldsfaktor DECIMAL(5,2),
    banklaan DECIMAL(12,2),
    realkreditlaan DECIMAL(12,2),
    samletlaan DECIMAL(12,2),
    alle_faste_udgifter DECIMAL(12,2),
    faste_udgifter_inkl_ydelser DECIMAL(12,2),
    raadighedsbeloeb DECIMAL(12,2),
    skabt_dato TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
